<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" xmlns:gz="http://gazebosim.org/schema">

  <!-- 
    Wheel Macro for Mecanum Drive
    Creates a mecanum wheel with visual, collision, and inertial properties
    Parameters:
      - prefix: wheel position identifier (front_left, rear_left, front_right, rear_right)
      - parent: parent link name
      - origin: position and orientation block
      - friction_dir: friction direction vector for mecanum physics
  -->
  
  <xacro:macro name="wheel" params="prefix parent friction_dir *origin">
    
    <!-- Wheel properties -->
    <xacro:property name="wheel_radius" value="0.05"/>
    <xacro:property name="wheel_width" value="0.02"/>
    <xacro:property name="wheel_mass" value="0.5"/>
    
    <!-- Wheel link -->
    <link name="wheel_${prefix}">
      <!-- Main tire -->
      <visual name="tire">
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="rubber_black"/>
      </visual>
      
      <!-- Wheel hub/rim -->
      <visual name="hub">
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius * 0.6}" length="${wheel_width + 0.005}"/>
        </geometry>
        <material name="metallic_grey"/>
      </visual>
      
      <!-- Hub center cap -->
      <visual name="hub_cap">
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius * 0.3}" length="${wheel_width + 0.01}"/>
        </geometry>
        <material name="dark_grey"/>
      </visual>
      
      <!-- Tread grooves indicators (decorative boxes) -->
      <visual name="tread_1">
        <origin xyz="${wheel_radius * 0.9} 0 0" rpy="0 ${pi/2} 0"/>
        <geometry>
          <box size="${wheel_width * 1.2} 0.003 0.005"/>
        </geometry>
        <material name="dark_grey"/>
      </visual>
      
      <visual name="tread_2">
        <origin xyz="0 ${wheel_radius * 0.9} 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <box size="${wheel_width * 1.2} 0.003 0.005"/>
        </geometry>
        <material name="dark_grey"/>
      </visual>
      
      <visual name="tread_3">
        <origin xyz="${-wheel_radius * 0.9} 0 0" rpy="0 ${pi/2} 0"/>
        <geometry>
          <box size="${wheel_width * 1.2} 0.003 0.005"/>
        </geometry>
        <material name="dark_grey"/>
      </visual>
      
      <visual name="tread_4">
        <origin xyz="0 ${-wheel_radius * 0.9} 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <box size="${wheel_width * 1.2} 0.003 0.005"/>
        </geometry>
        <material name="dark_grey"/>
      </visual>
      
      <!-- Collision with sphere for better mecanum simulation -->
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${wheel_radius}"/>
        </geometry>
      </collision>
      
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${wheel_mass}"/>
        <inertia 
          ixx="${(wheel_mass/12) * (3*wheel_radius*wheel_radius + wheel_width*wheel_width)}" 
          ixy="0.0" 
          ixz="0.0"
          iyy="${(wheel_mass/12) * (3*wheel_radius*wheel_radius + wheel_width*wheel_width)}" 
          iyz="0.0" 
          izz="${(wheel_mass/2) * wheel_radius * wheel_radius}"/>
      </inertial>
    </link>
    
    <!-- Wheel joint -->
    <joint name="wheel_${prefix}_joint" type="continuous">
      <xacro:insert_block name="origin"/>
      <parent link="${parent}"/>
      <child link="wheel_${prefix}"/>
      <axis xyz="0 1 0"/>
      <dynamics damping="0.05" friction="0.05"/>
    </joint>
    
    <!-- Gazebo properties for MECANUM wheel physics -->
    <gazebo reference="wheel_${prefix}">
      <material>Gazebo/Black</material>
      
      <!-- Mecanum-specific friction with directional vector -->
      <collision>
        <surface>
          <friction>
            <ode>
              <mu>1.5</mu>
              <mu2>0.0</mu2>
              <fdir1 gz:expressed_in="base_footprint">${friction_dir}</fdir1>
            </ode>
          </friction>
        </surface>
      </collision>
    </gazebo>
    
  </xacro:macro>

</robot>
