# SLAM Toolbox Configuration for AVG Robot
# Mode: Online Async SLAM (real-time mapping)
# Compatible with ROS 2 Jazzy + Gazebo Harmonic

slam_toolbox:
  ros__parameters:
    # === Simulation Settings ===
    use_sim_time: true
    
    # === Frame Configuration ===
    # TF tree: map -> odom -> base_link
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    
    # === Sensor Configuration ===
    scan_topic: /scan
    scan_queue_size: 10
    
    # === SLAM Mode ===
    # Options: mapping, localization
    mode: mapping
    
    # === Solver Configuration ===
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None
    
    # === Scan Matcher Configuration ===
    # Correlation search space configuration
    correlation_search_space_dimension: 0.5
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.1
    
    # Loop closure configuration
    loop_search_space_dimension: 8.0
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.03
    
    # Distance variance penalty
    distance_variance_penalty: 0.5
    angle_variance_penalty: 1.0
    
    # Fine search angle offset (radians)
    fine_search_angle_offset: 0.00349
    coarse_search_angle_offset: 0.349
    coarse_angle_resolution: 0.0349
    
    # Minimum angle penalty
    minimum_angle_penalty: 0.9
    minimum_distance_penalty: 0.5
    
    # Should use scan matching
    use_scan_matching: true
    use_scan_barycenter: true
    
    # === Scan Processing ===
    minimum_travel_distance: 0.2
    minimum_travel_heading: 0.2
    scan_buffer_size: 20
    scan_buffer_maximum_scan_distance: 15.0
    link_match_minimum_response_fine: 0.1
    link_scan_maximum_distance: 1.5
    
    # === Loop Closure ===
    do_loop_closing: true
    loop_match_minimum_chain_size: 10
    loop_match_maximum_variance_coarse: 3.0
    loop_match_minimum_response_coarse: 0.35
    loop_match_minimum_response_fine: 0.45
    
    # === Correlation Parameters ===
    # How much a map has to change to trigger a correlation update
    map_update_interval: 5.0
    
    # === Transform Publishing ===
    # Publish map->odom transform
    tf_buffer_duration: 30.0
    transform_publish_period: 0.02  # 50 Hz
    
    # === Map Settings ===
    resolution: 0.05  # 5 cm per pixel
    max_laser_range: 12.0  # Maximum range for LIDAR (meters)
    minimum_time_interval: 0.5
    transform_timeout: 0.2
    
    # === Occupancy Grid Settings ===
    minimum_free_space: 4.0
    occupied_space_cost: 100
    
    # === Optimization ===
    # Stack size for thread
    stack_size_to_use: 40000000  # 40MB
    
    # === Advanced Settings ===
    enable_interactive_mode: true
    debug_logging: false
    throttle_scans: 1  # Process every Nth scan (1 = all scans)
    
    # === Map Loading (For Localization Mode) ===
    # These parameters are for LOADING existing maps, not saving new ones
    # Only uncomment these when switching to localization mode with a saved map
    # map_file_name: /home/yossef/avg_autonomy/ros2_ws/src/avg_navigation/maps
    # map_start_pose: [0.0, 0.0, 0.0]
    # map_start_at_dock: true
