<?xml version="1.0"?>
<robot name="warehouse_agv" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Include all macro files -->
  <xacro:include filename="$(find avg_description)/urdf/materials.xacro"/>
  <xacro:include filename="$(find avg_description)/urdf/wheel_macro.xacro"/>
  <xacro:include filename="$(find avg_description)/urdf/sensor_macro.xacro"/>

  <!-- Robot Dimensions (properties) -->
  <xacro:property name="chassis_length" value="0.6"/>
  <xacro:property name="chassis_width" value="0.45"/>
  <xacro:property name="chassis_height" value="0.25"/>
  <xacro:property name="chassis_mass" value="15.0"/>
  
  <xacro:property name="wheel_radius" value="0.05"/>
  <xacro:property name="wheel_width" value="0.02"/>
  <xacro:property name="wheel_separation" value="0.4"/>
  <xacro:property name="wheelbase" value="0.45"/>
  
  <!-- Calculated offsets -->
  <xacro:property name="wheel_x_offset_front" value="${wheelbase/2}"/>
  <xacro:property name="wheel_x_offset_rear" value="${-wheelbase/2}"/>
  <xacro:property name="wheel_y_offset" value="${wheel_separation/2 + wheel_width/2}"/>
  <xacro:property name="wheel_z_offset" value="0"/>

  <!-- ========================================== -->
  <!-- Base Footprint Link (ground projection)    -->
  <!-- ========================================== -->
  <link name="base_footprint"/>

  <joint name="base_footprint_joint" type="fixed">
    <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
    <parent link="base_footprint"/>
    <child link="base_link"/>
  </joint>

  <!-- ========================================== -->
  <!-- Base Link (Chassis)                        -->
  <!-- ========================================== -->
  <link name="base_link">
    <!-- Main chassis base plate -->
    <visual name="base_plate">
      <origin xyz="0 0 0.02" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} 0.04"/>
      </geometry>
      <material name="metallic_grey"/>
    </visual>
    
    <!-- Chassis side panels -->
    <visual name="side_panel_left">
      <origin xyz="0 ${chassis_width/2 - 0.01} ${chassis_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_length} 0.02 ${chassis_height - 0.04}"/>
      </geometry>
      <material name="metallic_blue"/>
    </visual>
    
    <visual name="side_panel_right">
      <origin xyz="0 ${-chassis_width/2 + 0.01} ${chassis_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_length} 0.02 ${chassis_height - 0.04}"/>
      </geometry>
      <material name="metallic_blue"/>
    </visual>
    
    <!-- Front and rear panels -->
    <visual name="front_panel">
      <origin xyz="${chassis_length/2 - 0.01} 0 ${chassis_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="0.02 ${chassis_width - 0.04} ${chassis_height - 0.04}"/>
      </geometry>
      <material name="metallic_blue"/>
    </visual>
    
    <visual name="rear_panel">
      <origin xyz="${-chassis_length/2 + 0.01} 0 ${chassis_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="0.02 ${chassis_width - 0.04} ${chassis_height - 0.04}"/>
      </geometry>
      <material name="metallic_blue"/>
    </visual>
    
    <!-- Top cover plate -->
    <visual name="top_cover">
      <origin xyz="0 0 ${chassis_height - 0.02}" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_length - 0.02} ${chassis_width - 0.02} 0.04"/>
      </geometry>
      <material name="metallic_grey"/>
    </visual>
    
    <!-- Safety bumpers -->
    <visual name="front_bumper">
      <origin xyz="${chassis_length/2 + 0.015} 0 ${chassis_height/4}" rpy="0 0 0"/>
      <geometry>
        <box size="0.03 ${chassis_width - 0.1} 0.05"/>
      </geometry>
      <material name="yellow_warning"/>
    </visual>
    
    <visual name="rear_bumper">
      <origin xyz="${-chassis_length/2 - 0.015} 0 ${chassis_height/4}" rpy="0 0 0"/>
      <geometry>
        <box size="0.03 ${chassis_width - 0.1} 0.05"/>
      </geometry>
      <material name="yellow_warning"/>
    </visual>
    
    <!-- Cable conduits (decorative) -->
    <visual name="cable_conduit_left">
      <origin xyz="0 ${chassis_width/2 - 0.03} 0.06" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_length - 0.1} 0.015 0.015"/>
      </geometry>
      <material name="black"/>
    </visual>
    
    <visual name="cable_conduit_right">
      <origin xyz="0 ${-chassis_width/2 + 0.03} 0.06" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_length - 0.1} 0.015 0.015"/>
      </geometry>
      <material name="black"/>
    </visual>
    
    <!-- Electronics bay indicator -->
    <visual name="electronics_bay">
      <origin xyz="-0.1 0 ${chassis_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="0.2 0.15 ${chassis_height - 0.08}"/>
      </geometry>
      <material name="dark_grey"/>
    </visual>
    
    <!-- Collision (simplified) -->
    <collision>
      <origin xyz="0 0 ${chassis_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>
    
    <inertial>
      <origin xyz="0 0 ${chassis_height/2}" rpy="0 0 0"/>
      <mass value="${chassis_mass}"/>
      <inertia 
        ixx="${(chassis_mass/12) * (chassis_width*chassis_width + chassis_height*chassis_height)}"
        ixy="0.0" 
        ixz="0.0"
        iyy="${(chassis_mass/12) * (chassis_length*chassis_length + chassis_height*chassis_height)}"
        iyz="0.0"
        izz="${(chassis_mass/12) * (chassis_length*chassis_length + chassis_width*chassis_width)}"/>
    </inertial>
  </link>

  <!-- ========================================== -->
  <!-- Wheels (Using Wheel Macro)                 -->
  <!-- ========================================== -->
  
  <!-- Front Left Wheel -->
  <xacro:wheel prefix="front_left" parent="base_link">
    <origin xyz="${wheel_x_offset_front} ${wheel_y_offset} ${wheel_z_offset}" rpy="0 0 0"/>
  </xacro:wheel>

  <!-- Front Right Wheel -->
  <xacro:wheel prefix="front_right" parent="base_link">
    <origin xyz="${wheel_x_offset_front} ${-wheel_y_offset} ${wheel_z_offset}" rpy="0 0 0"/>
  </xacro:wheel>

  <!-- Rear Left Wheel -->
  <xacro:wheel prefix="rear_left" parent="base_link">
    <origin xyz="${wheel_x_offset_rear} ${wheel_y_offset} ${wheel_z_offset}" rpy="0 0 0"/>
  </xacro:wheel>

  <!-- Rear Right Wheel -->
  <xacro:wheel prefix="rear_right" parent="base_link">
    <origin xyz="${wheel_x_offset_rear} ${-wheel_y_offset} ${wheel_z_offset}" rpy="0 0 0"/>
  </xacro:wheel>

  <!-- ========================================== -->
  <!-- Sensors                                    -->
  <!-- ========================================== -->
  
  <!-- LIDAR - mounted on top center of chassis -->
  <xacro:lidar_sensor parent="base_link">
    <origin xyz="0 0 ${chassis_height + 0.035}" rpy="0 0 0"/>
  </xacro:lidar_sensor>

  <!-- IMU - near geometric center inside chassis -->
  <xacro:imu_sensor parent="base_link">
    <origin xyz="0 0 ${chassis_height/2}" rpy="0 0 0"/>
  </xacro:imu_sensor>

  <!-- Camera - front-mounted on chassis -->
  <xacro:camera_sensor parent="base_link">
    <origin xyz="${chassis_length/2 + 0.015} 0 ${chassis_height/2}" rpy="0 0 0"/>
  </xacro:camera_sensor>

  <!-- ========================================== -->
  <!-- Gazebo Plugins for gz sim (Gazebo Harmonic) -->
  <!-- ========================================== -->
  
  <!-- Differential drive controller plugin -->
  <gazebo>
    <plugin filename="gz-sim-diff-drive-system" name="gz::sim::systems::DiffDrive">
      <left_joint>wheel_front_left_joint</left_joint>
      <left_joint>wheel_rear_left_joint</left_joint>
      <right_joint>wheel_front_right_joint</right_joint>
      <right_joint>wheel_rear_right_joint</right_joint>
      <wheel_separation>${wheel_separation}</wheel_separation>
      <wheel_radius>${wheel_radius}</wheel_radius>
      <odom_publish_frequency>50</odom_publish_frequency>
      <max_linear_acceleration>1.0</max_linear_acceleration>
      <min_linear_acceleration>-1.0</min_linear_acceleration>
      <max_angular_acceleration>2.0</max_angular_acceleration>
      <min_angular_acceleration>-2.0</min_angular_acceleration>
      <max_linear_velocity>0.5</max_linear_velocity>
      <min_linear_velocity>-0.5</min_linear_velocity>
      <max_angular_velocity>1.0</max_angular_velocity>
      <min_angular_velocity>-1.0</min_angular_velocity>
      <topic>cmd_vel</topic>
      <odom_topic>odom</odom_topic>
      <tf_topic>/tf</tf_topic>
      <frame_id>odom</frame_id>
      <child_frame_id>base_footprint</child_frame_id>
      <publish_odom>true</publish_odom>
      <publish_odom_tf>true</publish_odom_tf>
      <publish_wheel_tf>false</publish_wheel_tf>
    </plugin>
  </gazebo>

  <!-- Joint state publisher plugin -->
  <gazebo>
    <plugin filename="gz-sim-joint-state-publisher-system" name="gz::sim::systems::JointStatePublisher">
      <topic>joint_states</topic>
      <update_rate>50</update_rate>
      <joint_name>wheel_front_left_joint</joint_name>
      <joint_name>wheel_front_right_joint</joint_name>
      <joint_name>wheel_rear_left_joint</joint_name>
      <joint_name>wheel_rear_right_joint</joint_name>
    </plugin>
  </gazebo>

  <!-- Pose publisher plugin -->
  <gazebo>
    <plugin filename="gz-sim-pose-publisher-system" name="gz::sim::systems::PosePublisher">
      <publish_link_pose>true</publish_link_pose>
      <publish_sensor_pose>false</publish_sensor_pose>
      <publish_collision_pose>false</publish_collision_pose>
      <publish_visual_pose>false</publish_visual_pose>
      <publish_nested_model_pose>false</publish_nested_model_pose>
      <update_frequency>50</update_frequency>
    </plugin>
  </gazebo>

</robot>
