<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- 
    Wheel Macro
    Creates a wheel with visual, collision, and inertial properties
    Parameters:
      - prefix: wheel position identifier (e.g., front_left, rear_right)
      - parent: parent link name
      - xyz: position offset [x, y, z]
      - rpy: orientation [roll, pitch, yaw]
  -->
  
  <xacro:macro name="wheel" params="prefix parent *origin">
    
    <!-- Wheel properties -->
    <xacro:property name="wheel_radius" value="0.05"/>
    <xacro:property name="wheel_width" value="0.02"/>
    <xacro:property name="wheel_mass" value="0.5"/>
    
    <!-- Wheel link -->
    <link name="wheel_${prefix}">
      <!-- Main tire -->
      <visual name="tire">
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="rubber_black"/>
      </visual>
      
      <!-- Wheel hub/rim -->
      <visual name="hub">
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius * 0.6}" length="${wheel_width + 0.005}"/>
        </geometry>
        <material name="metallic_grey"/>
      </visual>
      
      <!-- Hub center cap -->
      <visual name="hub_cap">
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius * 0.3}" length="${wheel_width + 0.01}"/>
        </geometry>
        <material name="dark_grey"/>
      </visual>
      
      <!-- Tread grooves indicators (decorative boxes) -->
      <visual name="tread_1">
        <origin xyz="${wheel_radius * 0.9} 0 0" rpy="0 ${pi/2} 0"/>
        <geometry>
          <box size="${wheel_width * 1.2} 0.003 0.005"/>
        </geometry>
        <material name="dark_grey"/>
      </visual>
      
      <visual name="tread_2">
        <origin xyz="0 ${wheel_radius * 0.9} 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <box size="${wheel_width * 1.2} 0.003 0.005"/>
        </geometry>
        <material name="dark_grey"/>
      </visual>
      
      <visual name="tread_3">
        <origin xyz="${-wheel_radius * 0.9} 0 0" rpy="0 ${pi/2} 0"/>
        <geometry>
          <box size="${wheel_width * 1.2} 0.003 0.005"/>
        </geometry>
        <material name="dark_grey"/>
      </visual>
      
      <visual name="tread_4">
        <origin xyz="0 ${-wheel_radius * 0.9} 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <box size="${wheel_width * 1.2} 0.003 0.005"/>
        </geometry>
        <material name="dark_grey"/>
      </visual>
      
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
      
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${wheel_mass}"/>
        <inertia 
          ixx="${(wheel_mass/12) * (3*wheel_radius*wheel_radius + wheel_width*wheel_width)}" 
          ixy="0.0" 
          ixz="0.0"
          iyy="${(wheel_mass/12) * (3*wheel_radius*wheel_radius + wheel_width*wheel_width)}" 
          iyz="0.0" 
          izz="${(wheel_mass/2) * wheel_radius * wheel_radius}"/>
      </inertial>
    </link>
    
    <!-- Wheel joint -->
    <joint name="wheel_${prefix}_joint" type="continuous">
      <xacro:insert_block name="origin"/>
      <parent link="${parent}"/>
      <child link="wheel_${prefix}"/>
      <axis xyz="0 1 0"/>
      <dynamics damping="0.05" friction="0.05"/>
    </joint>
    
    <!-- Gazebo properties for MECANUM/OMNI wheel physics -->
    <gazebo reference="wheel_${prefix}">
      <material>Gazebo/Black</material>
      
      <!-- Omnidirectional friction (equal in all directions for mecanum) -->
      <mu1>1.0</mu1>   <!-- Primary friction -->
      <mu2>1.0</mu2>   <!-- Secondary friction (equal for omni movement) -->
      
      <!-- Contact physics - Optimized for mecanum -->
      <kp>1000000.0</kp>     <!-- Contact stiffness -->
      <kd>10.0</kd>          <!-- Contact damping -->
      <minDepth>0.001</minDepth>
      <maxVel>100.0</maxVel>
      <maxContacts>1</maxContacts>  <!-- Single contact point per wheel -->
      
      <!-- Mecanum wheels need some slip in all directions -->
      <slip1>0.1</slip1>
      <slip2>0.1</slip2>
      
      <!-- Surface properties for consistent behavior -->
      <bounce>0.0</bounce>
      <bounce_threshold>100000</bounce_threshold>
      <soft_cfm>0.0</soft_cfm>
      <soft_erp>0.2</soft_erp>
    </gazebo>
    
  </xacro:macro>

</robot>
